"""Add document verification workflow

Revision ID: 515228811996
Revises: 2f3dcb128724
Create Date: 2026-07-04 15:45:46.737975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515228811996'
down_revision = '2f3dcb128724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
