"""Create education histories table

Revision ID: f06910150f98
Revises: e794f3932635
Create Date: 2026-07-02 17:18:01.890143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06910150f98'
down_revision = 'e794f3932635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_profile_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('index_number', sa.String(length=30), nullable=False),
    sa.Column('exam_year', sa.Integer(), nullable=False),
    sa.Column('mean_grade', sa.String(length=5), nullable=False),
    sa.Column('certificate_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['applicant_profile_id'], ['applicant_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_profile_id'),
    sa.UniqueConstraint('index_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education_histories')
    # ### end Alembic commands ###
