"""Add document review fields

Revision ID: f513f0770e75
Revises: 515228811996
Create Date: 2026-07-04 18:09:50.837991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f513f0770e75'
down_revision = '515228811996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by')

    # ### end Alembic commands ###
