from .user import User
from .department import Department
from .course import Course
from .applicant_profile import ApplicantProfile
from .education_history import EducationHistory
from .application import Application
from .uploaded_document import UploadedDocument
from .application_log import ApplicationLog
from .admission_letter import AdmissionLetter
